---
title: "project!!!!!"
output: html_notebook
---

```{r link cloned repo so you can pull/commit/push}
# RUN THESE ALL ONCE!!! un-comment the code blocks as you go
#install.packages(c("usethis", "gitcreds"))

# then run this:
#usethis::create_github_token()

# which opens GitHub in your browser, generate a token
# COPY it before closing the page

# run this and paste token into terminal when prompted
#gitcreds::gitcreds_set()

# done! :) make sure to re-comment the code blocks

# hi its tarilyn
```

1. Exploratory Analysis and Model Specification

```{r libaries, include=FALSE}
# make sure to download any you dont have with: install.packages("package_name")
library(here)
library(corrplot)
library(tidyverse)
```


```{r prep}
Demographic <- read.table(here("data", "Demographic.txt")) # more robust read-in

# change column names to match correct variables
colnames(Demographic) <- c('ID','County','state','Land_area','total_population',
                          'Population_18to34','Population_65','Physicians','beds',
                          'Y_i','Graduate_highschool','Graduate_Bachelor','below_poverty',
                          'unemployment','capita_income','personal_income','Geographic_region')
Demographic2 <- Demographic

# Variable names and dimensions of the table
head(Demographic2)
names(Demographic2)
dim(Demographic2)
summary(Demographic2)

Demographic2$Y_i <- log(Demographic$Y_i) # log transform Y

colnames(Demographic2)[10] <- "LogY_i"

region1 <- Demographic2[Demographic2$Geographic_region == 1,]
region2 <- Demographic2[Demographic2$Geographic_region == 2,]
region3 <- Demographic2[Demographic2$Geographic_region == 3,]
region4 <- Demographic2[Demographic2$Geographic_region == 4,]

n1<-nrow(region1)
n2<-nrow(region2)
n3<-nrow(region3)
n4<-nrow(region4)
```


```{r corr plots, warning=FALSE}
# general corr
cor(Demographic2[,4:17])
corrplot(cor(Demographic2[,4:17]))

# per region corr
regions <- list(region1, region2, region3, region4)
top_list <- list()

for (i in seq_along(regions)) {
  
  cat("FOR REGION: ", i, "\n")
  
  region <- regions[[i]]
  cors <- sapply(region[, 4:17], function(x) cor(x, region$LogY_i))
  ranked <- sort(abs(cors), decreasing = TRUE)
  
  top_list[[i]] <- head(ranked, 5)
  
  corrplot(cor(region$LogY_i, region[,4:17]))
  
  print(top_list[[i]])
}
```
```{r}
# Region 1
# log(Y_i) = Beta_0 + Beta_1*total_population

boxplot(cbind(region1$LogY_i,region1$below_poverty, region1$unemployment),names = c("Total serious crimes (log-scale)", "Poverty Levels", "Percent Unemployment"))

pairs(cbind(region1$LogY_i, region1$below_poverty, region1$total_population), labels = c("Total serious crimes", "Poverty Level", "Total population"), lwd = 4)

pairs(cbind(region1$LogY_i, region1$below_poverty, region1$total_population),labels=c("Total serious crimes  (log-scale)","Poverty level ", "Poverty Levels", "Total Population"), lwd=4)

pairs(cbind(region1$LogY_i, region1$below_poverty, log(region1$total_population)), labels = c("Total serious crimes (log-scale)","Poverty Levels", "Total population (log-scale)"), lwd = 4)
```
```{r}
# Region 3
# Question 2

Y <- Demographic2$LogY_i[Demographic$Geographic_region == 3]
X <- Demographic2$personal_income[Demographic$Geographic_region == 3]

model_3 <- lm(Y ~ X, data = region_3)

# Computations:

Y_hat <- fitted(model_3)
e <- residuals(model_3)

SSE <- sum(e^2)
MSE <- SSE / (n3 - 2)

X_bar <- mean(X)

s_b0 <- sqrt(MSE * ((1 / n3) + (X_bar)^2 / (sum((X - X_bar)^2))))
s_b1 <- sqrt(MSE / (sum((X - X_bar)^2)))

b0 <- coef(model_3)[[1]]
b1 <- coef(model_3)[[2]]

t_val <- qt(0.975, n3 - 2)

b0_lwr <- b0 - t_val * s_b0
b0_upr <- b0 + t_val * s_b0

b1_lwr <- b1 - t_val * s_b1
b1_upr <- b1 + t_val * s_b1

Y_bar <- mean(Y)

SSR <- sum((Y_hat - Y_bar)^2)
SSTO <- sum((Y - Y_bar)^2)

R2 <- SSR / SSTO

# Residual plots:

plot(
  Y_hat, e,
  pch = 19,
  xlab = "Fitted Values",
  ylab = "Residuals",
  main = "Residual Plot Against Fitted Values"
)

abline(h = 0, col = "blue", lwd = 2)

qqnorm(
  residuals(model_3),
  pch = 19,
)

qqline(residuals(model_3), col = "red", lwd = 2)

# Final values:

b0_lwr
b0_upr

b1_lwr
b1_upr
R2
```
